### ISSUE TITLE
Question: Partial in UPDATE Methods

### ISSUE THREAD

**Issue by johannesschobel** [kelvin-mai/nest-ideas-api#1]
Dear @kelvin-mai ,

first of all: This tutorial is awesome :tada: **Really** nice work!

I have a question regarding the use of the `Partial<Entity>` in your `update(...)` methods, like in the linked code snippet for the controller:
https://github.com/kelvin-mai/nest-ideas-api/blob/66c9f5feef65cf6181d5b6f3011573609468be00/src/idea/idea.controller.ts#L57-L67

and the corresponding service:
https://github.com/kelvin-mai/nest-ideas-api/blob/66c9f5feef65cf6181d5b6f3011573609468be00/src/idea/idea.service.ts#L91-L110

As far as i understood, the `Partial<IdeaDTO>` only tells, that it must be an `IdeaDTO`, but it must not be "fully filled" (e.g., not all values must be present). Wouldn't it be better to "remove" the `Partial` part and directly use the `IdeaDTO` in this case and use the `@IsOptional()` decorator from the `class-validator` package?

My thought process is as follows:
Consider the example, where you have different `DTOs` based on the operation you are calling (e.g., a `CreateUserDTO` and `UpdateUserDTO`). For the `CreateUserDTO` you may provide different attributes than for the `UpdateUserDTO` (like, the user is not allowed to change his username after registration).

This way you could enforce the user, that he **must** send certain attributes with the request (e.g., they must be present!). For example, in order to change your user-profile you **must** send the current password to prove your identity!

Further, it would be much cleaner, if you use `Swagger` as well - you would use the `@ApiModelPropertyOptional()` decorator on the attributes that are flagged as `@IsOptional()`. This way, 

This would look something like this:
```ts
export class UpdateUserDTO {

   @IsOptional()
   @IsString()   
   @ApiModelPropertyOptional({ type: 'string' })
   firstname?: string;

   @IsOptional()
   @IsString()
   @ApiModelPropertyOptional({ type: 'string' })
   lastname?: string;

   // additional attributes that may be set optionally here
   
   @IsString()
   @MinLength(8)
   @ApiModelProperty({ type: 'string', minLength: 8 })
   password: string;
}
```

What do you think about this? Or am I missing something crucial here?!
Of course, the corresponding `Entity` class may needs to have optional attributes as well (e.g., it may be the case that the `firstname` will never be set) - or you use `default` values from `TypeORM`..

I would love to hear your thoughts on this...

All the best

**Comment by kelvin-mai** [comment]
You definitely can, and it's good practice if you prefer explicit strong types for each operation. I just went with the route with less code overhead as I thought it was more dry. It may be a lot less explicit and type safe, but I felt that it was more DRY. I don't think either method is wrong though, it just depends on your preference.

**Comment by johannesschobel** [comment]
Dear @kelvin-mai ,
thanks for your input on this. I think, for a "production ready" application one should use different DTOs. Further, you should "only-allow-whitelisted-attributes" in your class-validator as this would raise an error if someone passes `customAttribute: true` to your endpoints..
